---
- name: make sure pasword file present
  file: path={{ ocserv_config_dir}}/passwd state=touch

- name: ensure absent of tmp file for password
  file: path={{ ocserv_config_dir}}/passwd.in.tmp state=absent

- name: add user for ocserv server
  shell: echo "{{item.password}}" >> {{ ocserv_config_dir }}/passwd.in.tmp &&
         echo "{{item.password}}" >> {{ ocserv_config_dir }}/passwd.in.tmp &&
         ocpasswd -c {{ ocserv_config_dir }}/passwd {{item.username}} 0<{{ ocserv_config_dir }}/passwd.in.tmp &&
         rm {{ ocserv_config_dir }}/passwd.in.tmp
  with_items: "{{ ocserv_users }}"
  tags:
    - ocserv
    - add_user
